CREATE DATABASE IF NOT EXISTS lab_mysql;

USE lab_mysql;

DROP TABLE IF EXISTS `Invoices`;
DROP TABLE IF EXISTS `Cars`;
DROP TABLE IF EXISTS `Customers`;
DROP TABLE IF EXISTS `Salesperson`;

CREATE TABLE IF NOT EXISTS `Cars` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`VIN` VARCHAR(255) NOT NULL,
	`year` INTEGER NOT NULL,
	`model` VARCHAR(255) NOT NULL,
	`manufacturer` VARCHAR(255) NOT NULL,
	`color` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Customers` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`customer_ID` INTEGER NOT NULL,
	`email` VARCHAR(255),
	`address` VARCHAR(255) NOT NULL,
	`country` VARCHAR(255) NOT NULL,
	`city` VARCHAR(255) NOT NULL,
	`state/province` VARCHAR(255) NOT NULL,
	`zip/postal code` VARCHAR(255) NOT NULL,
	`phone_number` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Salesperson` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`staff_ID` INTEGER NOT NULL,
	`store` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Invoices` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`invoice_number` INTEGER NOT NULL,
	`customer_ID` INTEGER UNSIGNED NOT NULL,
	`salesperson_ID` INTEGER UNSIGNED NOT NULL,
	`car_ID` INTEGER UNSIGNED NOT NULL,
	`date` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `Invoices`
ADD FOREIGN KEY(`car_ID`) REFERENCES `Cars`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Invoices`
ADD FOREIGN KEY(`salesperson_ID`) REFERENCES `Salesperson`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Invoices`
ADD FOREIGN KEY(`customer_ID`) REFERENCES `Customers`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;